apiVersion: v1
kind: Template
metadata:
  name: app-sre-errbot
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: app-sre-errbot
    name: app-sre-errbot
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: app-sre-errbot
    template:
      metadata:
        labels:
          app: app-sre-errbot
      spec:
        containers:
        - name: app-sre-errbot
          image: ${IMAGE}:${IMAGE_TAG}
          env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-sre-errbot
                key: SLACK_TOKEN
          - name: GQL_SERVER
            valueFrom:
              secretKeyRef:
                name: app-sre-errbot
                key: GQL_SERVER
          - name: GQL_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-sre-errbot
                key: GQL_TOKEN
          - name: BOT_ADMINS
            value: "${BOT_ADMINS}"
          - name: ACCESS_CONTROLS_ALLOWROOMS
            value: "${ACCESS_CONTROLS_ALLOWROOMS}"
          - name: BOT_ALT_PREFIXES
            value: "${BOT_ALT_PREFIXES}"
          ports:
          - containerPort: 2112
            name: metrics
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
          - name: data
            mountPath: /opt/app-root/errbot/data
        volumes:
        - name: data
          emptyDir: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: app-sre-errbot
    name: app-sre-errbot
  spec:
    selector:
      app: app-sre-errbot
    ports:
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
    type: ClusterIP
- apiVersion: v1
  kind: Secret
  metadata:
    name: app-sre-errbot
  data:
    SLACK_TOKEN: Y2hhbmdlbWU=
    GQL_SERVER: Y2hhbmdlbWU=
    GQL_TOKEN: Y2hhbmdlbWU=
parameters:
- name: IMAGE
  value: quay.io/app-sre/app-sre-errbot
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "1"
- name: BOT_ADMINS
  value: "@jchevret"
  description: "comma separated list of bot admins"
- name: ACCESS_CONTROLS_ALLOWROOMS
  value: "#sd-app-sre-teamchat,#sd-app-sre-sandbox"
  description: "comma separated list of allowed rooms"
- name: BOT_ALT_PREFIXES
  value: "@app-sre-bot"
  description: "comma separated list of bot alternate prefixes"
